import type { EndpointMeta, PromotionMode } from "@/types/studio";

/** The two interchangeable promotion-pricing endpoints the mode switch governs. */
export const PROMOTION_ENDPOINT_IDS = ["promotion-execution", "get-member-promotions"];

/**
 * The promotion endpoint that should answer for a given mode.
 * "auto" returns null = both endpoints answer normally (no guarding).
 */
export function activePromotionEndpoint(mode: PromotionMode): string | null {
  if (mode === "gpm") return "promotion-execution";
  if (mode === "gmp") return "get-member-promotions";
  return null;
}

export const ENDPOINTS: EndpointMeta[] = [
  {
    id: "oauth-token",
    name: "OAuth Token",
    method: "POST",
    mockPath: "/api/oauth/token",
    sfPath: "/services/oauth2/token",
    group: "Auth",
    available: "—",
    description: "Salesforce OAuth 2.0 token endpoint. Returns a fake bearer token the cartridge can cache and re-use.",
  },
  {
    id: "promotion-execution",
    name: "Promotion Evaluation & Execution",
    method: "POST",
    mockPath: "/api/loyalty/promotion-execution",
    sfPath: "/services/data/v65.0/global-promotions-management/promotion-execution",
    group: "Promotions",
    available: "65.0",
    description: "THE pricing call. Send a cart; get back the adjusted cart + line items with the discount amounts already computed. Requires Global Promotions Management (GPM) in the real org.",
  },
  {
    id: "get-member-promotions",
    name: "Get Member Promotions (alt)",
    method: "POST",
    mockPath: "/api/loyalty/get-member-promotions",
    sfPath: "/services/data/v65.0/connect/loyalty/programs/{programName}/program-processes/GetMemberPromotions",
    group: "Promotions",
    available: "56.0",
    description: "ALTERNATIVE to Promotion Evaluation & Execution (set the adapter's PROMOTION_API to GET_MEMBER_PROMOTIONS). A program process returning the member's eligible promotions. The response shape is IMPLEMENTER-DEFINED — these fixtures are a plausible default, not doc-confirmed.",
  },
  {
    id: "promotion-reward",
    name: "Promotion Reward Application",
    method: "POST",
    mockPath: "/api/loyalty/promotion-reward",
    sfPath: "/services/data/v65.0/global-promotions-management/promotion-reward",
    group: "Promotions",
    available: "65.0",
    description: "Order-placement step: create transaction journals for the order and accrue the promotion rewards (points, vouchers, etc.).",
  },
  {
    id: "eligible-promotions",
    name: "Eligible Promotions List",
    method: "POST",
    mockPath: "/api/loyalty/eligible-promotions",
    sfPath: "/services/data/v67.0/global-promotions-management/eligible-promotions",
    group: "Promotions",
    available: "60.0",
    description: "Get eligible promotions and their associated rewards for a cart and its line items, or for a Loyalty Program Member. When used in a Loyalty context, this resource checks PromotionPartyUsage for the member and excludes promotions whose usage limit is reached. The request root XML tag is CartInputMapRepresentation; the response is the \"Eligible Promotions List\" schema (a `promotions` array of Promotion Details). Optional query parameter ruleLibraryApiName selects an active Global Promotion Management Rule Library when multiple are configured.",
  },
  {
    id: "promotion-recommendations",
    name: "Promotion Recommendations",
    method: "POST",
    mockPath: "/api/loyalty/promotion-recommendations",
    sfPath: "/services/data/v67.0/promotions/recommendation/product-promotion",
    group: "Promotions",
    available: "64.0",
    description: "Retrieve the list of promotions recommended for a customer or a loyalty program member based on the product and personalization point. Accepts a personalizationPoint and a member/customer identifier (membershipNumber+loyaltyProgramId, loyaltyProgramMemberId, or individualId) plus optional dataspace and eligibleChannel. Optional query params: count (max recommendations) and promotionsPerProductLimit (max promotions per product). Returns recommendationCount, personalizationId, and a recommendationList of ranked promotion details.",
  },
  {
    id: "coupon-usage-increase",
    name: "Coupon Usage Increase",
    method: "POST",
    mockPath: "/api/loyalty/coupon-usage-increase",
    sfPath: "/services/data/v67.0/global-promotions-management/coupons/usage-increase",
    group: "Promotions",
    available: "63.0",
    description: "Increase the usage count of a list of coupons. Takes a list of coupon codes plus the redeeming customer and transaction context, and returns a per-coupon result (success with remaining redemption counts, or failure with an error message). The request's externalTransactionNumber must match the value sent to the decrease-usage API so usage is tracked correctly for the originating transaction.",
  },
  {
    id: "coupon-usage-decrease",
    name: "Coupon Usage Decrease",
    method: "POST",
    mockPath: "/api/loyalty/coupon-usage-decrease",
    sfPath: "/services/data/v67.0/global-promotions-management/coupons/usage-decrease",
    group: "Promotions",
    available: "63.0",
    description: "Decrease the usage count of a list of coupons. POST request takes a list of coupon codes plus the originating transaction details; response (schema \"Coupon Usage\", which wraps a list of \"Coupon Usage Result\" entries) reports per-coupon success/failure with redemption-limit counts remaining.",
  },
  {
    id: "promotion-enrollments",
    name: "Promotion Enrollment",
    method: "POST",
    mockPath: "/api/loyalty/promotion-enrollments",
    sfPath: "/services/data/v67.0/global-promotions-management/promotion-enrollments",
    group: "Promotions",
    available: "67.0",
    description: "Enrolls a customer (account or contact) in an enrollment-eligible promotion. POST to /global-promotions-management/promotion-enrollments with an inputParameters array of Enrollment Details Input. Returns a Promotion Enrollment body containing a results array of Enrollment Details, each including the assigned promotionPartyUsageId used to track promotion usage for that customer.",
  },
  {
    id: "enroll-in-promotion",
    name: "Enroll In Promotion (process)",
    method: "POST",
    mockPath: "/api/loyalty/enroll-in-promotion",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/EnrollInPromotion",
    group: "Promotions",
    available: "56.0",
    description: "Loyalty program process that enrolls a loyalty member into a promotion. Invoked via POST to the program-processes/EnrollInPromotion endpoint of a named loyalty program. The request wraps inputs in a processParameters array; documented examples use either MemberId+PromotionId or MembershipNumber+PromotionName. The response is the standard Loyalty Process Output envelope (message, outputParameters, simulationDetails, status), with the inner outputParameters.results containing the enrolled MemberId and the created LoyaltyProgramMbrPromotionId. Request and response field sets are partly org-configured: they vary depending on the input/output parameters configured for the EnrollInPromotion process type in the Salesforce org.",
  },
  {
    id: "voucher-list",
    name: "Member Vouchers",
    method: "GET",
    mockPath: "/api/loyalty/vouchers",
    sfPath: "/services/data/v58.0/loyalty/programs/{programName}/members/{membershipNumber}/vouchers",
    group: "Vouchers",
    available: "58.0",
    description: "Returns the vouchers issued to a member. Filter with ?voucherStatus=Issued. Statuses: Issued | Reserved | Redeemed | Expired | Cancelled.",
  },
  {
    id: "voucher-redeem",
    name: "Voucher Action (Reserve / Reinstate / Redeem)",
    method: "POST",
    mockPath: "/api/loyalty/vouchers/redeem",
    sfPath: "/services/data/v62.0/loyalty/programs/{programName}/members/{membershipNumber}/vouchers/{voucherCode}/redeem",
    group: "Vouchers",
    available: "62.0",
    description: "One resource, three actions via the body `action` field (type ReservationAction, since API v62.0): Reserve (Issued→Reserved, returns a reservationKey), Reinstate (Reserved→Issued, the 'release'), Redeem (→Redeemed; default when no action is sent). Pick the matching scenario per action.",
  },
  {
    id: "issue-voucher",
    name: "Issue Voucher (process)",
    method: "POST",
    mockPath: "/api/loyalty/issue-voucher",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/${programName}/program-processes/IssueVoucher",
    group: "Vouchers",
    available: "56.0",
    description: "Loyalty Program Process invoked via POST that runs the IssueVoucher process template to issue a new voucher to a loyalty member. The request wrapper is the standard `processParameters` array; its inner fields and the response `outputParameters.results` items are implementer-defined per the loyalty program process configured in the org. Resource is the generic Loyalty Program Process endpoint (/connect/loyalty/programs/${programName}/program-processes/${processName}), with processName=IssueVoucher.",
  },
  {
    id: "cancel-voucher",
    name: "Cancel Voucher (process)",
    method: "POST",
    mockPath: "/api/loyalty/cancel-voucher",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/CancelVoucher",
    group: "Vouchers",
    available: "56.0",
    description: "Loyalty program process that changes the status of a voucher to canceled. Invoked as a configured loyalty program process via POST to /connect/loyalty/programs/{programName}/program-processes/{processName} (processName = CancelVoucher). The request body is wrapped in the standard processParameters array; the doc shows two input variants: (1) MemberId + VoucherId, or (2) MembershipNumber + VoucherCode. The response is a Loyalty Process Output object (message, outputParameters, simulationDetails, status). Request and response parameters vary by the input/output parameters configured for the CancelVoucher process type in a given Salesforce org, so exact field sets are org-configured.",
  },
  {
    id: "member-info",
    name: "Member Profile",
    method: "GET",
    mockPath: "/api/loyalty/members",
    sfPath: "/services/data/v67.0/loyalty-programs/{programName}/members",
    group: "Members",
    available: "55.0",
    description: "Member lookup by ?membershipNumber=. Documented Member Profile Output: identity in associatedContact, points in memberCurrencies[], tier in memberTiers[].",
  },
  {
    id: "member-benefits",
    name: "Member Benefits",
    method: "GET",
    mockPath: "/api/loyalty/member-benefits",
    sfPath: "/services/data/v67.0/connect/loyalty/member/${memberId}/memberbenefits",
    group: "Members",
    available: "51.0",
    description: "Get benefits for a loyalty program member. Returns the output representation of all benefits available for a member (memberBenefits array of Member Benefit Output). Resource path /connect/loyalty/member/${memberId}/memberbenefits; GET only; Requires Chatter: No.",
  },
  {
    id: "engagement-trail",
    name: "Member Engagement Trail",
    method: "GET",
    mockPath: "/api/loyalty/engagement-trail",
    sfPath: "/services/data/vXX.X/loyalty/programs/${programName}/members/${membershipNumber}/engagement-trail?$promotionId={promotionId}",
    group: "Members",
    available: "63.0",
    description: "Fetches current and target values of the milestones defined in an engagement trail and the rewards received after achieving milestones. GET resource under Members. Requires the promotionId query parameter (Required, 63.0). Path params: programName (Required) and membershipNumber (Required). Response body schema: Member Engagement Trail Output (available version 62.0 for response fields).",
  },
  {
    id: "update-member-details",
    name: "Update Member Details (process)",
    method: "POST",
    mockPath: "/api/loyalty/update-member-details",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/UpdateMemberDetails",
    group: "Members",
    available: "56.0",
    description: "Update personal and preference details of a loyalty member. This is a Loyalty Program Process invoked via POST to /connect/loyalty/programs/{programName}/program-processes/UpdateMemberDetails. It is the shared \"Run a Loyalty Program Process\" resource (Available version 56.0, HTTP method POST). The request body wraps inputs in a processParameters array (Loyalty Process Parameter Map); the response is a Loyalty Process Output object. Per the doc, the specific request and response parameters vary depending on the input/output parameters configured for the UpdateMemberDetails process type in the Salesforce org.",
  },
  {
    id: "tier-processing",
    name: "Tier Processing (process)",
    method: "POST",
    mockPath: "/api/loyalty/tier-processing",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/TierProcessing",
    group: "Members",
    available: "56.0",
    description: "Invokes the TierProcessing loyalty program process to upgrade or downgrade a loyalty member's tier. It's a Loyalty Program Process run via POST /connect/loyalty/programs/{programName}/program-processes/{processName} with processName=TierProcessing. The standard request wrapper is processParameters (a Loyalty Process Parameter Map); the response is a Loyalty Process Output object. The exact request/response fields vary depending on the input and output parameters configured for the TierProcessing process type in a given Salesforce org.",
  },
  {
    id: "individual-member-enrollment",
    name: "Individual Member Enrollment",
    method: "POST",
    mockPath: "/api/loyalty/individual-member-enrollment",
    sfPath: "/services/data/vXX.X/loyalty-programs/${loyaltyProgramName}/individual-member-enrollments",
    group: "Enrollment",
    available: "55.0",
    description: "Enroll an individual member in a loyalty program. Creates a person account and an Individual type loyalty program member record for the new member. Requires Person Accounts enabled in the org, and the executing user's profile must have Person Account selected as the default record type for person accounts. HTTP method POST. Root XML tag <individualMemberEnrollment>. Response schema: Individual Member Enrollment.",
  },
  {
    id: "corporate-member-enrollment",
    name: "Corporate Member Enrollment",
    method: "POST",
    mockPath: "/api/loyalty/corporate-member-enrollment",
    sfPath: "/services/data/vXX.X/loyalty-programs/${loyaltyProgramName}/corporate-member-enrollments",
    group: "Enrollment",
    available: "55.0",
    description: "Enroll corporate members in a loyalty program. Creates a business account and a Corporate type loyalty program member record for the new member. Requires Person Accounts enabled in the org; the executing user's profile must have Business Account as the default record type for business accounts. Optionally creates transaction journals to credit enrollment/referral points.",
  },
  {
    id: "unenroll-member",
    name: "Unenroll Member (process)",
    method: "POST",
    mockPath: "/api/loyalty/unenroll-member",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/UnenrollMember",
    group: "Enrollment",
    available: "56.0",
    description: "Unenroll a member from a loyalty program. This is a Loyalty PROGRAM PROCESS invoked via POST to the generic program-processes resource with the process name \"UnenrollMember\". The standard request wrapper is processParameters; you identify the member either by MemberId or by CurrentMembershipNumber. The documented success response returns the unenrolled member's MemberId inside outputParameters.outputParameters.results. The request and response parameters vary depending on the input/output parameters configured for the UnenrollMember process type in a given Salesforce org, so most field names beyond the standard wrapper (processParameters / message / outputParameters / simulationDetails / status) are org-configured.",
  },
  {
    id: "transaction-history",
    name: "Transaction History",
    method: "POST",
    mockPath: "/api/loyalty/transaction-history",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/transaction-history",
    group: "Transactions",
    available: "56.0",
    description: "Recent transaction journals for the member. POST (not GET) with a body { membershipNumber, journalType: Accrual|Redemption, periodStartDate, periodEndDate } + ?page=. Output: { message, status, totalCount, transactionJournals[] } with PascalCase journal fields.",
  },
  {
    id: "transaction-ledger-summary",
    name: "Transaction Ledger Summary",
    method: "GET",
    mockPath: "/api/loyalty/transaction-ledger-summary",
    sfPath: "/services/data/v67.0/loyalty/programs/${programName}/members/${membershipNumber}/transaction-ledger-summary",
    group: "Transactions",
    available: "58.0",
    description: "Retrieve an aggregate view on the transaction journal and the loyalty ledger records for a loyalty program member. GET-only resource. Supports query params: journalSubTypeName, additionalTransactionJournalAttributes, journalTypeName, pageNumber (200 journals/page, sorted by created date, first page by default), periodEndDate, periodStartDate. The resource definition names the response body \"Transaction Journal Summary Output\", but the actual documented schema with a JSON example and property table in the Response Bodies section is \"Transaction Ledgers\" (description: \"Output representation of the transaction journals and the ledgers associated with the specified loyalty program member\"), referencing the Transaction Details Output and Points Change Output sub-schemas.",
  },
  {
    id: "credit-points",
    name: "Credit Points To Members (process)",
    method: "POST",
    mockPath: "/api/loyalty/credit-points",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/{processName}",
    group: "Transactions",
    available: "56.0",
    description: "Loyalty Program Process that runs the CreditPointsToMembers process template to credit pre-calculated points to a loyalty member on every transaction. Invoked as POST /connect/loyalty/programs/{programName}/program-processes/{processName} where processName is the name of a process created from the CreditPointsToMembers template (e.g. CreditPointsToMembers or a custom-cloned process). The standard request wrapper is processParameters (a Loyalty Process Parameter Map); the response is a Loyalty Process Output. The actual inner request/response parameters are implementer-defined and vary per org configuration, so only the documented sample fields are reproduced here.",
  },
  {
    id: "debit-points",
    name: "Debit Points From Members (process)",
    method: "POST",
    mockPath: "/api/loyalty/debit-points",
    sfPath: "/services/data/v67.0/connect/loyalty/programs/{programName}/program-processes/DebitPointsFromMembers",
    group: "Transactions",
    available: "56.0",
    description: "Run the DebitPointsFromMembers loyalty program process to redeem a loyalty member's pre-calculated points on a transaction. This is a Loyalty Program Process invoked via POST to /connect/loyalty/programs/{programName}/program-processes/{processName} (processName=DebitPointsFromMembers). The request is wrapped in the standard processParameters array (Loyalty Process Parameter Map); the response body schema is \"Loyalty Process Output\". The exact input/output parameters are org-configured per the process definition, but the developer guide gives concrete sample request and response JSON.",
  },
  {
    id: "transaction-journals-execution",
    name: "Transaction Journals Execution",
    method: "POST",
    mockPath: "/api/loyalty/transaction-journals-execution",
    sfPath: "/services/data/vXX.X/connect/realtime/loyalty/programs/{programName}",
    group: "Transactions",
    available: "54.0",
    description: "Creates and processes a list of transaction journals against a corresponding loyalty program process. The loyalty program processes determine how transaction journals are processed; when transaction journals meet the criteria and conditions for a program process, the actions set up in the process are triggered. The request can supply full transaction journal details (for journals not yet in the org) or a list of IDs of existing transaction journals (ID-based input supported in v55.0+). Promotion limits configured on PromotionLimit records are NOT automatically enforced; to enforce them, call Eligible Promotions List (POST) first and pass the returned promotions as the appliedPromotions array. Response body schema: Loyalty Engine Realtime Output.",
  },
  {
    id: "transaction-journals-simulation",
    name: "Transaction Journals Simulation",
    method: "POST",
    mockPath: "/api/loyalty/transaction-journals-simulation",
    sfPath: "/services/data/vXX.X/connect/realtime/loyalty/programs/${programName}",
    group: "Transactions",
    available: "55.0",
    description: "Runs a simulation to determine how transaction journals are processed against their corresponding loyalty program processes. When transaction journals meet the criteria and conditions for a program process, actions set up in the process are triggered for the transaction journals. POST to /connect/realtime/loyalty/programs/${programName} with a loyaltyEngineInput body containing transactionJournals and runSetting.isSimulation=true. Response is the Loyalty Engine Realtime Output representation.",
  },
  {
    id: "link-member-partner",
    name: "Link Program Member Partner",
    method: "POST",
    mockPath: "/api/loyalty/link-member-partner",
    sfPath: "/services/data/v66.0/loyalty/programs/{programName}/members/{membershipNumber}/partners/{partnerName}/link",
    group: "Partners",
    available: "66.0",
    description: "Links a loyalty program member with a specified partner program, enabling integration between loyalty members and partner ecosystems so members can earn, redeem, and manage benefits across connected programs. Resource path: /loyalty/programs/{programName}/members/{membershipNumber}/partners/{partnerName}/link. Documented HTTP method is POST (the task expected PUT — doc says POST). Request body (Link Program Member Partner Input): optional externalId (String) and additionalAttributes (Object). Response body (Link Program Member Partner): linkNumber (String), message (String, nullable), status (Boolean).",
  },
  {
    id: "unlink-member-partner",
    name: "Unlink Program Member Partner",
    method: "POST",
    mockPath: "/api/loyalty/unlink-member-partner",
    sfPath: "/services/data/v66.0/loyalty/programs/{programName}/members/{membershipNumber}/partners/{partnerName}/unlink",
    group: "Partners",
    available: "66.0",
    description: "Unlinks an existing association between a loyalty program member and a partner program. The API securely removes the linkage and updates related records to ensure data consistency across loyalty and partner systems. A record is uniquely identified by membershipNumber and partnerName.",
  },
  {
    id: "club-member-enrollment",
    name: "Club Member Enrollment",
    method: "POST",
    mockPath: "/api/loyalty/club-member-enrollment",
    sfPath: "/services/data/v64.0/loyalty-programs/{programName}/clubs/{clubName}/member-enrollment",
    group: "Clubs",
    available: "64.0",
    description: "Enroll members in a club and manage their details, including membership numbers, renewal periods, and end dates. Supports enrolling an existing loyalty program member, an existing contact, a new person, an existing account, or a new account.",
  },
  {
    id: "club-member-profile",
    name: "Club Member Profile",
    method: "GET",
    mockPath: "/api/loyalty/club-member-profile",
    sfPath: "/club/members",
    group: "Clubs",
    available: "64.0",
    description: "Get the profile details of a club member such as membership number, contact ID, and loyalty program name. GET /club/members with query parameters (clubMembershipNumber, clubName, contactId, loyaltyMembershipNumber, programName). Returns the Club Member Details response body, which embeds arrays of Club Member Benefits and Club Member Promotions.",
  },
  {
    id: "club-membership-renewal",
    name: "Club Membership Renewal",
    method: "POST",
    mockPath: "/api/loyalty/club-membership-renewal",
    sfPath: "/services/data/v64.0/loyalty-programs/${loyaltyProgramName}/clubs/${clubName}/membership-renewal",
    group: "Clubs",
    available: "64.0",
    description: "Renew the membership of club members and manage their membership details such as membership numbers, renewal periods, and end dates. Resource path uses ${loyaltyProgramName} (use \"Club Program\" for an Independent Club) and ${clubName} URI parameters. POST request body supplies the club membership number, renewal period and type, and optional notes/external identifier/order item. Response returns the renewed clubMembershipNumber and clubMembershipEndDate.",
  },
  {
    id: "promotions-manage",
    name: "Promotions (Create / List)",
    method: "POST",
    mockPath: "/api/loyalty/promotions-manage",
    sfPath: "/services/data/v67.0/global-promotions-management/promotions",
    group: "Admin",
    available: "64.0",
    description: "Promotions Creation (POST, PUT) — Create a promotion based on the provided promotion limits and eligibility conditions. The request body carries promotionDetails (Unified Promotions Input[]) and rules (Unified Promotion Template Input[]). The response body schema is \"Promotion\": the output representation of the promotion with rule configuration (promotionConfigurationWarnings, promotionDetails as Unified Promotions Output[], rules as Template Configuration[]). Resource: /global-promotions-management/promotions.",
  },
  {
    id: "promotion-detail",
    name: "Promotion (Get / Update)",
    method: "GET",
    mockPath: "/api/loyalty/promotion-detail",
    sfPath: "/services/data/v67.0/global-promotions-management/promotions/{promotionId}",
    group: "Admin",
    available: "60.0",
    description: "Promotion Details (GET, PUT). GET retrieves the details of a promotion; PUT updates a promotion record (the promotion must first be deactivated in the org before update). Resource path: /global-promotions-management/promotions/promotionId. The response is the \"Promotion\" output representation, which wraps the \"Unified Promotions\" promotion-details object and a list of rule template configurations.",
  },
  {
    id: "promotion-configuration",
    name: "Promotion Configuration",
    method: "GET",
    mockPath: "/api/loyalty/promotion-configuration",
    sfPath: "/services/data/v67.0/global-promotions-management/promotions/{promotionId}/configuration",
    group: "Admin",
    available: "61.0",
    description: "View configuration of a promotion, including its definition, eligibility criteria, rules, limits, and related rule library version. Enables developers and system integrators to view the configuration of active promotions and export it to external systems such as offline POS systems. Only available in orgs where Global Promotions Management is available. The promotionId must belong to a promotion whose rules are configured using a non-Loyalty promotion template. Optional repeatable query param relatedObjectAndFieldApiNames (String[]) selects related object fields to include (one field per object, as ObjectApiName.FieldApiName).",
  },
  {
    id: "promotion-rule-configuration",
    name: "Promotion Rule Configuration",
    method: "GET",
    mockPath: "/api/loyalty/promotion-rule-configuration",
    sfPath: "/services/data/v67.0/global-promotions-management/promotions/{promotionId}/rule-configuration",
    group: "Admin",
    available: "60.0",
    description: "Fetch the rule configuration details for a given promotion ID. Defines how a promotion works by combining eligibility criteria (event), rewards logic (reward), priority, journal type/subtype, and template-driven behavior. A promotion can contain multiple rules ordered by priority. The GET response body is \"Template List Configuration\" (a wrapper with a single `rules` array of \"Template Configuration\" objects). The same resource also supports POST to create rule configuration (request body has event, journalSubType, journalSubTypeName, journalType, priority, promotionLimit, reward, ruleName, templateName; POST response body is \"Unified Promotion Templates\").",
  },
];

export function getEndpoint(id: string): EndpointMeta | undefined {
  return ENDPOINTS.find((e) => e.id === id);
}
